apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-api-user
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-api-user
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80